#!/bin/sh
set -e

# config file
DEFAULT=/etc/default/sslh
. $DEFAULT

case "$1" in
    configure)
	# if sslh user doesn't exists, create it
        if ! getent passwd sslh > /dev/null
        then
            echo "Adding system-user for sslh daemon"
            adduser --system --group --quiet --home /nonexistent --no-create-home --disabled-login sslh
        fi

		if command -v invoke-rc.d >/dev/null 2>&1
		then
			invoke-rc.d sslh start
		else
			/etc/init.d/sslh start
		fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
