#!/bin/sh
set -e

case "$1" in
	purge)
		# delete sslh daemon user
		# test if exists just to don't generate error
		if getent passwd sslh > /dev/null
		then
			if [ -x "$(which deluser)" ]
			then
				echo "Deleting sslh user"
				deluser --quiet sslh > /dev/null || true
			fi
		fi
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
	;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
