#!/bin/sh
set -e

# config file
DEFAULT=/etc/default/sslh
. $DEFAULT

case "$1" in
    configure)
	# if sslh user doesn't exists, create it
        if ! getent passwd sslh > /dev/null
        then
            echo "Adding system-user for sslh daemon"
            adduser --system --group --quiet --home /nonexistent --no-create-home --disabled-login sslh
        fi

        rm -f /etc/init.d/sslh

        if dpkg --compare-versions "$2" lt-nl "1.18-1pexip4"; then
            systemctl disable sslh.service
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
